// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-rest v1.3.0
// - protoc             v5.27.0
// source: health.proto

package health

import (
	context "context"
	server "github.com/asjard/asjard/core/server"
	rest "github.com/asjard/asjard/pkg/server/rest"
)

func _Health_Check_RestHandler(ctx *rest.Context, srv any, interceptor server.UnaryServerInterceptor) (any, error) {
	in := new(HealthCheckRequest)
	if interceptor == nil {
		return srv.(HealthServer).Check(ctx, in)
	}
	info := &server.UnaryServerInfo{
		Server:     srv,
		FullMethod: "asjard.api.health.Health.Check",
		Protocol:   rest.Protocol,
	}
	handler := func(ctx context.Context, req any) (any, error) {
		return srv.(HealthServer).Check(ctx, in)
	}
	return interceptor(ctx, in, info, handler)
}

// HealthRestServiceDesc is the rest.ServiceDesc for Health service.
// It's only intended for direct use with rest.AddHandler,
// and not to be introspected or modified (even as a copy)
var HealthRestServiceDesc = rest.ServiceDesc{
	ServiceName: "asjard.api.health.Health",
	HandlerType: (*HealthServer)(nil),
	Methods: []rest.MethodDesc{
		{
			MethodName: "Check",
			Desc:       ".",
			Method:     "GET",
			Path:       "/health",
			Handler:    _Health_Check_RestHandler,
		},
	},
}
